### ISSUE TITLE
Python 3.11环境报错

### ISSUE THREAD

**Issue by NewTrees** [renoyuan/easyofd#21]
1
saving xml 1_xml
Traceback (most recent call last):
  File "D:\Laiye\CodeProjects\PythonProjects\ofdtopdf\src\test.py", line 38, in <module>
    test_ofd2(ofd_file_path)
  File "D:\Laiye\CodeProjects\PythonProjects\ofdtopdf\src\test.py", line 19, in test_ofd2
    ofd.read(ofdb64,save_xml=True, xml_name=f"{file_prefix}_xml") # 读取ofdb64
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Laiye\CodeProjects\PythonProjects\ofdtopdf\env\Lib\site-packages\easyofd\ofd.py", line 46, in read
    self.data = OFDParser(ofd_f)(save_xml=save_xml, xml_name=xml_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Laiye\CodeProjects\PythonProjects\ofdtopdf\env\Lib\site-packages\easyofd\parser_ofd\ofd_parser.py", line 343, in __call__
    return self.parser()
           ^^^^^^^^^^^^^
  File "D:\Laiye\CodeProjects\PythonProjects\ofdtopdf\env\Lib\site-packages\easyofd\parser_ofd\ofd_parser.py", line 250, in parser
    f.write(self.get_xml_obj(SignedValue))
TypeError: write() argument must be str, not None

**Comment by renoyuan** [comment]
ofd 文件发我看下

**Comment by NewTrees** [comment]
@renoyuan 您好，我已经邮件发给您了，麻烦您看看，谢谢

**Comment by renoyuan** [comment]
已解决，可以尝试更新easyofd代码库再试下

**Comment by NewTrees** [comment]
已经转换成功，谢谢！
