### ISSUE TITLE
easyofd.draw.font_tools:register_font:96 - register_font_error: 'name'

### ISSUE THREAD

**Issue by CellMook** [renoyuan/easyofd#23]
代码：demo.py中的 test_ofd2

错误信息：| ERROR    | easyofd.draw.font_tools:register_font:96 - register_font_error:
'name'
Traceback (most recent call last):
  File "D:\anaconda3\envs\py312\Lib\site-packages\easyofd\draw\font_tools.py", line 91, in register_font
    pdfmetrics.registerFont(TTFont(FontName, file_name))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\py312\Lib\site-packages\reportlab\pdfbase\ttfonts.py", line 1192, in __init__
    self.face = TTFontFace(filename, validate=validate, subfontIndex=subfontIndex)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\py312\Lib\site-packages\reportlab\pdfbase\ttfonts.py", line 1073, in __init__
    TTFontFile.__init__(self, filename, validate=validate, subfontIndex=subfontIndex)
  File "D:\anaconda3\envs\py312\Lib\site-packages\reportlab\pdfbase\ttfonts.py", line 440, in __init__
    self.extractInfo(charInfo)
  File "D:\anaconda3\envs\py312\Lib\site-packages\reportlab\pdfbase\ttfonts.py", line 471, in extractInfo
    name_offset = self.seek_table("name")
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\py312\Lib\site-packages\reportlab\pdfbase\ttfonts.py", line 291, in seek_table
    self._pos = self.get_table_pos(tag)[0] + offset_in_table
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\py312\Lib\site-packages\reportlab\pdfbase\ttfonts.py", line 276, in get_table_pos
    offset = self.table[tag]['offset']
             ~~~~~~~~~~^^^^^
KeyError: 'name'

**Comment by renoyuan** [comment]
ofd文件发我

**Comment by CellMook** [comment]
发邮箱了

**Comment by renoyuan** [comment]
该文件的字体 为自定义的OpenType 内嵌字体，目前不支持解析和转换。
