### ISSUE TITLE
环境是Ubuntu20.04,python3.11.9,easyofd0.4.0,安装了windows下的所有字体，还是报错。能帮忙看看吗。

### ISSUE THREAD

**Issue by xujh-0522** [renoyuan/easyofd#31]
2024-09-14 08:43:13.607 | WARNING  | easyofd.parser_ofd:<module>:24 - FONT  registerFont failed COURI.TTF: Courier New
2024-09-14 08:43:13.607 | WARNING  | easyofd.parser_ofd:<module>:24 - FONT  registerFont failed COURI.TTF: CourierNewPSMT
2024-09-14 08:43:13.607 | WARNING  | easyofd.parser_ofd:<module>:24 - FONT  registerFont failed COURI.TTF: CourierNew
2024-09-14 08:43:13.607 | WARNING  | easyofd.parser_ofd:<module>:24 - FONT  registerFont failed COURI.TTF: SWCRMF+CourierNewPSMT
2024-09-14 08:43:13.608 | WARNING  | easyofd.parser_ofd:<module>:24 - FONT  registerFont failed COURI.TTF: SWANVV+CourierNewPSMT
2024-09-14 08:43:13.847 | WARNING  | easyofd.parser_ofd.ofd_parser:jb22png:117 - 未安装jbig2dec，无法处理jb2文件
signatures_xml_obj ['Doc_0/Signs/Signatures.xml'] {'ofd:Signatures': {'@xmlns:ofd': 'http://www.ofdspec.org/2016', 'ofd:MaxSignId': '2', 'ofd:Signature': {'@ID': '2', '@BaseLoc': '/Doc_0/Signs/Sign_0/Signature.xml'}}}
signatures_info {'PageRef': '1', 'Boundary': '90.00 8.00 30.00 20.00', 'ID': '1', 'SignedValue': '//Doc_0/Signs/Sign_0/SignedValue.dat'}
2024-09-14 08:43:13.848 | INFO     | easyofd.ofd:to_pdf:72 - to_pdf
page_size_details [[0.0, 0.0, 210.0, 140.0]]
2024-09-14 08:43:13.852 | ERROR    | easyofd.draw.draw_pdf:__call__:468 - 'Courier New'
2024-09-14 08:43:13.852 | ERROR    | easyofd.draw.draw_pdf:__call__:469 - ofd解析失败
Traceback (most recent call last):
  File "/miniconda/envs/vanna/lib/python3.11/site-packages/reportlab/pdfbase/pdfmetrics.py", line 697, in getFont
    return _fonts[fontName]
           ~~~~~~^^^^^^^^^^
KeyError: 'Courier New'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/envs/vanna/lib/python3.11/site-packages/easyofd/draw/draw_pdf.py", line 465, in __call__
    self.draw_pdf()
  File "/miniconda/envs/vanna/lib/python3.11/site-packages/easyofd/draw/draw_pdf.py", line 443, in draw_pdf
    self.draw_chars(c, text_list, fonts, page_size)
  File "/miniconda/envs/vanna/lib/python3.11/site-packages/easyofd/draw/draw_pdf.py", line 145, in draw_chars
    c.setFont(font, line_dict["size"] * self.OP)
  File "/miniconda/envs/vanna/lib/python3.11/site-packages/reportlab/pdfgen/canvas.py", line 1738, in setFont
    font = pdfmetrics.getFont(self._fontname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/envs/vanna/lib/python3.11/site-packages/reportlab/pdfbase/pdfmetrics.py", line 699, in getFont
    return findFontAndRegister(fontName)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/envs/vanna/lib/python3.11/site-packages/reportlab/pdfbase/pdfmetrics.py", line 681, in findFontAndRegister
    face = getTypeFace(fontName)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/envs/vanna/lib/python3.11/site-packages/reportlab/pdfbase/pdfmetrics.py", line 638, in getTypeFace
    return _typefaces[faceName]
           ~~~~~~~~~~^^^^^^^^^^
KeyError: 'Courier New'


fc-list |grep Courier 
显示有Courier New字体相关的文件。
/usr/share/fonts/my_fonts/courbi.ttf: Courier New:style=Bold Italic,Negreta cursiva,tučné kurzíva,fed kursiv,Fett Kursiv,Έντονα Πλάγια,Negrita Cursiva,Lihavoitu Kursivoi,Gras Italique,Félkövér dőlt,Grassetto Corsivo,Vet Cursief,Halvfet Kursiv,Pogrubiona kursywa,Negrito Itálico,Полужирный Курсив,Tučná kurzíva,Fet Kursiv,Kalın İtalik,Krepko poševno,đậm nghiêng,Lodi etzana
/usr/share/fonts/truetype/msttcorefonts/courbi.ttf: Courier New:style=Bold Italic,Negreta cursiva,tučné kurzíva,fed kursiv,Fett Kursiv,Έντονα Πλάγια,Negrita Cursiva,Lihavoitu Kursivoi,Gras Italique,Félkövér dőlt,Grassetto Corsivo,Vet Cursief,Halvfet Kursiv,Pogrubiona kursywa,Negrito Itálico,Полужирный Курсив,Tučná kurzíva,Fet Kursiv,Kalın İtalik,Krepko poševno,Lodi etzana
/usr/share/fonts/truetype/msttcorefonts/Courier_New_Italic.ttf: Courier New:style=Italic,Cursiva,kurzíva,kursiv,Πλάγια,Kursivoitu,Italique,Dőlt,Corsivo,Cursief,Kursywa,Itálico,Курсив,İtalik,Poševno,nghiêng,Etzana
/usr/share/fonts/truetype/msttcorefonts/couri.ttf: Courier New:style=Italic,Cursiva,kurzíva,kursiv,Πλάγια,Kursivoitu,Italique,Dőlt,Corsivo,Cursief,Kursywa,Itálico,Курсив,İtalik,Poševno,nghiêng,Etzana
/usr/share/fonts/my_fonts/couri.ttf: Courier New:style=Italic,Cursiva,kurzíva,kursiv,Πλάγια,Kursivoitu,Italique,Dőlt,Corsivo,Cursief,Kursywa,Itálico,Курсив,İtalik,Poševno,nghiêng,Etzana
/usr/share/fonts/truetype/msttcorefonts/Courier_New.ttf: Courier New:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,thường,Arrunta
/usr/share/fonts/my_fonts/Courier-BOLDITALIC-1.ttf: Courier:style=BOLDITALIC
/usr/share/fonts/truetype/msttcorefonts/cour.ttf: Courier New:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,thường,Arrunta
/usr/share/fonts/truetype/msttcorefonts/courbd.ttf: Courier New:style=Bold,Negreta,tučné,fed,Fett,Έντονα,Negrita,Lihavoitu,Gras,Félkövér,Grassetto,Vet,Halvfet,Pogrubiony,Negrito,Полужирный,Fet,Kalın,Krepko,đậm,Lodia
/usr/share/fonts/truetype/msttcorefonts/Courier_New_Bold.ttf: Courier New:style=Bold,Negreta,tučné,fed,Fett,Έντονα,Negrita,Lihavoitu,Gras,Félkövér,Grassetto,Vet,Halvfet,Pogrubiony,Negrito,Полужирный,Fet,Kalın,Krepko,đậm,Lodia
/usr/share/fonts/my_fonts/cour-2.ttf: Courier New:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,thường,Arrunta
/usr/share/fonts/my_fonts/cour.ttf: Courier New:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,thường,Arrunta
/usr/share/fonts/truetype/msttcorefonts/Courier_New_Bold_Italic.ttf: Courier New:style=Bold Italic,Negreta cursiva,tučné kurzíva,fed kursiv,Fett Kursiv,Έντονα Πλάγια,Negrita Cursiva,Lihavoitu Kursivoi,Gras Italique,Félkövér dőlt,Grassetto Corsivo,Vet Cursief,Halvfet Kursiv,Pogrubiona kursywa,Negrito Itálico,Полужирный Курсив,Tučná kurzíva,Fet Kursiv,Kalın İtalik,Krepko poševno,Lodi etzana
/usr/share/fonts/my_fonts/courbd.ttf: Courier New:style=Bold,Negreta,tučné,fed,Fett,Έντονα,Negrita,Lihavoitu,Gras,Félkövér,Grassetto,Vet,Halvfet,Pogrubiony,Negrito,Полужирный,Fet,Kalın,Krepko,đâ ̣m,Lodia

**Comment by renoyuan** [comment]
看上去就是字体的问题，你把ofd文件发我看看

**Comment by yuege969** [comment]
> 看上去就是字体的问题，你把ofd文件发我看看

请问解决了吗，我也遇到了同样的问题

**Comment by thend-wk** [comment]
我也遇到了一样的问题，看系统中字体已经有了，不过还是报了注册失败并找不到key 你们解决了没 @yuege969 @xu

**Comment by yuege969** [comment]
> 我也遇到了一样的问题，看系统中字体已经有了，不过还是报了注册失败并找不到key 你们解决了没
@thend-wk 你也可以尝试一下，希望对你有所帮助
我这边是回退了版本到0.3.1，并修改easyofd相关源码之后， 暂时无使用异常
/opt/conda/lib/python3.8/site-packages/easyofd/draw/draw_ofd.py，对应实际的python路径， 第53行修改为：
```
def build_document_res(self, img_len: int = 0, id_obj: CurId = None, pfd_res_uuid_map=None):
```

**Comment by thend-wk** [comment]
> > 我也遇到了一样的问题，看系统中字体已经有了，不过还是报了注册失败并找不到key 你们解决了没
> > [@thend-wk](https://github.com/thend-wk) 你也可以尝试一下，希望对你有所帮助
> > 我这边是回退了版本到0.3.1，并修改easyofd相关源码之后， 暂时无使用异常
> > /opt/conda/lib/python3.8/site-packages/easyofd/draw/draw_ofd.py，对应实际的python路径， 第53行修改为：
> 
> ```
> def build_document_res(self, img_len: int = 0, id_obj: CurId = None, pfd_res_uuid_map=None):
> ```

OKK，我试试，感谢大佬

**Comment by thend-wk** [comment]
> > > 我也遇到了一样的问题，看系统中字体已经有了，不过还是报了注册失败并找不到key 你们解决了没
> > > [@thend-wk](https://github.com/thend-wk) 你也可以尝试一下，希望对你有所帮助
> > > 我这边是回退了版本到0.3.1，并修改easyofd相关源码之后， 暂时无使用异常
> > > /opt/conda/lib/python3.8/site-packages/easyofd/draw/draw_ofd.py，对应实际的python路径， 第53行修改为：
> > 
> > 
> > ```
> > def build_document_res(self, img_len: int = 0, id_obj: CurId = None, pfd_res_uuid_map=None):
> > ```
> 
> OKK，我试试，感谢大佬

奇怪，我这回退到0.3.1，修改了那个文件，好像还是报那个错，KeyError: 'Courier New'
