### ISSUE TITLE
ofd转pdf的时候报错

### ISSUE THREAD

**Issue by my-fastcms** [renoyuan/easyofd#36]
def ofd_to_pdf(self, ofd_file_path):
        output_pdf_path = ofd_file_path[:-4] + ".pdf"
        with open(ofd_file_path, "rb") as f:
            ofdb64 = f.read()
            ofd = OFD()  # 初始化OFD 工具类
            ofd.read(ofdb64, fmt = "binary")  # 读取ofdb64
            # print(ofd.data) # ofd.data 为程序解析结果
            pdf_bytes = ofd.to_pdf()  # 转pdf

            with open(output_pdf_path, "wb") as f:
                f.write(pdf_bytes)

Traceback (most recent call last):
  File "D:\robot_develop\code\approval_robot\service\ChuZhengService.py", line 113, in ofd_to_pdf
    ofd.read(ofdb64, fmt = "binary")  # 读取ofdb64
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\robot_develop\Miniconda3\envs\crawler_robot\Lib\site-packages\easyofd\ofd.py", line 51, in read
    self.data = OFDParser(ofd_f)(save_xml=save_xml, xml_name=xml_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\robot_develop\Miniconda3\envs\crawler_robot\Lib\site-packages\easyofd\parser_ofd\ofd_parser.py", line 350, in __call__
    self.file_tree = FileRead(self.ofdb64)(save_xml=save_xml, xml_name=xml_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\robot_develop\Miniconda3\envs\crawler_robot\Lib\site-packages\easyofd\parser_ofd\file_deal.py", line 77, in __call__
    self.buld_file_tree()
  File "D:\robot_develop\Miniconda3\envs\crawler_robot\Lib\site-packages\easyofd\parser_ofd\file_deal.py", line 63, in buld_file_tree
    if "xml" not in file else xmltodict.parse(open(f"{abs_path}" , "r", encoding="utf-8").read())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\robot_develop\Miniconda3\envs\crawler_robot\Lib\site-packages\xmltodict.py", line 359, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: duplicate attribute: line 2, column 64

**Comment by renoyuan** [comment]
ofd 文件发我
