### ISSUE TITLE
报错：OSError: [WinError 145] 目录不是空的。: 'D:\\pythonProject\\金融机构查询请求文件交互系统\\监委查询/128084_37ac171c-b21f-11ef-a533-6c4b90c73c79'

### ISSUE THREAD

**Issue by cztanghao** [renoyuan/easyofd#39]
我的代码是批量读取很多ofd文件，然后提取关键信息到excel里，在使用extract_ofd(ofd.data)时报错：
Traceback (most recent call last):
  File "D:\pythonProject\金融机构查询请求文件交互系统\监委查询\监委登记台账全2.py", line 118, in <module>
    main1(path, input_date, suffix)
  File "D:\pythonProject\金融机构查询请求文件交互系统\监委查询\监委登记台账全2.py", line 41, in main1
    ofd.read(file, fomat="path")
  File "D:\python3.8.10\lib\site-packages\easyofd\ofd.py", line 47, in read
    self.data = OFDParser(ofd_f)(save_xml=save_xml, xml_name=xml_name) 
  File "D:\python3.8.10\lib\site-packages\easyofd\parser_ofd\ofd_parser.py", line 256, in __call__
    self.file_tree = FileRead(self.ofdb64)(save_xml=save_xml,xml_name=xml_name)
  File "D:\python3.8.10\lib\site-packages\easyofd\parser_ofd\file_deal.py", line 77, in __call__
    self.buld_file_tree()
  File "D:\python3.8.10\lib\site-packages\easyofd\parser_ofd\file_deal.py", line 67, in buld_file_tree
    shutil.rmtree(self.unzip_path)
  File "D:\python3.8.10\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\python3.8.10\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "D:\python3.8.10\lib\shutil.py", line 620, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] 目录不是空的。: 'D:\\pythonProject\\金融机构查询请求文件交互系统\\监委查询/128084_37ac171c-b21f-11ef-a533-6c4b90c73c79'

Process finished with exit code 1

[Desktop.zip](https://github.com/user-attachments/files/18022489/Desktop.zip)

**Comment by renoyuan** [comment]
你这个是什么版本得？
拉下最新版本的输入改为ofdb64试下

**Comment by renoyuan** [comment]
https://github.com/renoyuan/easyofd/tree/master/test
/demo.py

**Comment by cztanghao** [comment]
file_prefix = os.path.splitext(os.path.split(file_path)[1])[0]
    with open(file_path, "rb") as f:
        ofdb64 = str(base64.b64encode(f.read()), "utf-8")
    ofd = OFD()  # 初始化OFD 工具类
    ofd.read(ofdb64, save_xml=True, xml_name=f"{file_prefix}_xml")  # 读取ofdb64
    # print("ofd.data", ofd.data) # ofd.data 为程序解析结果
    pdf_bytes = ofd.to_pdf()  # 转pdf

    ofd.del_data()
    
    我试用上面的代码成功避开了报错，但是生成了很多文件和文件夹，ofd.del_data()好像不能删掉生成的文件和文件夹，求助怎么解决。

**Comment by renoyuan** [comment]
save_xml=True 去掉

**Comment by cztanghao** [comment]
收到，谢谢

**Comment by cztanghao** [comment]
收到，谢谢

**Comment by cztanghao** [comment]
save_xml=False，之后又报错osError了，不知道怎么解决。
